# Generated by Django 3.1.5 on 2021-01-10 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tejidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partes', models.IntegerField()),
                ('temperatura', models.FloatField()),
                ('color', models.FloatField()),
                ('inflamacion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Grafo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conectado', models.BooleanField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='app.tejidos')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='app.tejidos')),
            ],
        ),
    ]
